### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by tpeczek** [tpeczek/Lib.AspNetCore.WebSocketsCompression#1]
This issue is for general feedback regarding this project.

**Comment by tpeczek** [comment]
@deandob @RyanLamansky @zygimantas

As you were interested in https://github.com/aspnet/WebSockets/issues/19 I'm reaching out to you for some feedback.

I've created this library because I was in need and as I've decided to open source it I would want to make sure it is useful for others. The initial version was designed to be used in place of Microsoft.AspNetCore.WebSockets. If you are still interested in subject of WebSocket per-message compression in ASP.NET Core I would love to hear from you.

**Comment by deandob** [comment]
Yes, interested thanks tpeczek. Won't get a chance to test it until October & will provide feedback then.

**Comment by Michael-Tajmajer-Emrsn** [comment]
I had success using your package with dot net core.

When I targeted net461 it failed.  The first issue was that net461 Deflate doesn't add the                 if LAST_FOUR_OCTETS_OF_EMPTY_NON_COMPRESSED_DEFLATE_BLOCK.  It seems that the block it creates is fine as is.

Adjusting TrimLastFourOctetsOfEmptyNonCompressedDeflateBlock() with a check for 0 solved that:

if(0 != lastFourOctetsOfEmptyNonCompressedDeflateBlockPosition)
    Array.Resize(ref compressedMessagePayload, lastFourOctetsOfEmptyNonCompressedDeflateBlockPosition);

But, the socket will still error when running under net461.  Do you have any thoughts on what to look at?

To test, I adjusted the demo project (attached).
[Demo.AspNetCore.WebSockets.csproj.txt](https://github.com/tpeczek/Lib.AspNetCore.WebSocketsCompression/files/3153121/Demo.AspNetCore.WebSockets.csproj.txt)

**Comment by tpeczek** [comment]
@Michael-Tajmajer-Emrsn I'll be honest I haven't used this much with .NET Framework (only some smoke tests back in the day). I should have a couple free hours on Friday so I'll sit down to it and take a look.

**Comment by Michael-Tajmajer-Emrsn** [comment]
Thank you for the response.  No rush for us, we've decided to wait until our code is moved over to dotnet core, which does work well!

**Comment by tpeczek** [comment]
@Michael-Tajmajer-Emrsn Thank you for letting me know. In general, you've got me interested in what might be going on, so I'll probably take a look anyway.

**Comment by tpeczek** [comment]
Closing as project is being archived in favor of built-in [WebSocket compression](https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-6-preview-6/#websocket-compression) coming in ASP.NET Core 6.
