### ISSUE TITLE
WebSocketDeflateCompressionProvider.cs has a bug 

### ISSUE THREAD

**Issue by fxh-git** [tpeczek/Lib.AspNetCore.WebSocketsCompression#4]
return SendMessageAsync(webSocket, compressedMessagePayload, WebSocketMessageType.Text, true, cancellationToken) 
 WebSocketMessageType.Text should change to messageType

**Comment by tpeczek** [comment]
Closing as project is being archived in favor of built-in [WebSocket compression](https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-6-preview-6/#websocket-compression) coming in ASP.NET Core 6.
