### ISSUE TITLE
Can you provide a demo about sending an receiving message by binarymessage?

### ISSUE THREAD

**Issue by zsuxiong** [tpeczek/Lib.AspNetCore.WebSocketsCompression#5]
Server side Code ：  
byte[] messageArray = System.Text.Encoding.UTF8.GetBytes(message);
                connectionsTasks.Add(connection.SendAsync(messageArray, cancellationToken));

Is That Right? I Can't Decode By Js:
  var decoder = new TextDecoder("utf-8");   
        var result= decoder.decode(new Uint8Array(message.data)); 
        console.log(result);

Need your Help,Thanks

**Comment by tpeczek** [comment]
To be honest, I never tried sending text as binary.

I'll take a look at your example as soon as I'll have time, but the probably will not be before weekend.

**Comment by zsuxiong** [comment]
To&nbsp;Tomasz Pęczek:
Thank you very much.
I Change CompressBinaryMessageAsync function，use CompressTextWithDeflateAsync instead of CompressBinaryWithDeflateAsync，then it is ok。




&nbsp;public override async Task CompressBinaryMessageAsync(WebSocket webSocket, byte[] message, CancellationToken cancellationToken)
&nbsp; &nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; var msg1 = Encoding.UTF8.GetString(message);
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; byte[] compressedMessagePayload = await CompressTextWithDeflateAsync(msg1);
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;// byte[] compressedMessagePayload = await CompressBinaryWithDeflateAsync(message);&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; await SendCompressedMessageAsync(webSocket, compressedMessagePayload, WebSocketMessageType.Binary, true, cancellationToken);
&nbsp; &nbsp; &nbsp; &nbsp; }



This is my demo:https://testws.feixiaoquan.com/


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Tomasz Pęczek"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月5日(星期二) 晚上6:57
收件人:&nbsp;"tpeczek/Lib.AspNetCore.WebSocketsCompression"<Lib.AspNetCore.WebSocketsCompression@noreply.github.com&gt;;
抄送:&nbsp;"开心"<275970369@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [tpeczek/Lib.AspNetCore.WebSocketsCompression] Can you provide a demo about sending an receiving message by binarymessage? (#5)





 
To be honest, I never tried sending text as binary.
 
I'll take a look at your example as soon as I'll have time, but the probably will not be before weekend.

**Comment by tpeczek** [comment]
Closing as project is being archived in favor of built-in [WebSocket compression](https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-6-preview-6/#websocket-compression) coming in ASP.NET Core 6.
